django/test_project2/test_polar/urls.py
from django.urls import path, re_path
from test_polar import views

app_name = "test_polar"

urlpatterns = [
    # re_path(r"^add_ttype/$", views.add_ttype, name="addttype")
    path("", views.redirect_to_home, name="tohome"),
    path("home/", views.select_collections, name="selectcol"),
    path("summary/", views.show_polar, name="showpolar"),
    path(
        "summary/return_lapdata/<str:fname>",
        views.show_lapdata,
        name="showlapdata",
    ),
    path("adapt/", views.start_adapt, name="startadapt"),
    path("adapt/form/<str:fname>", views.show_adapt, name="showadapt"),
    path("adapt/formlap/<str:fname>", views.show_adaptlap, name="showadaptlap"),
    path("adapt/formlap/", views.adapt_distance, name="adaptlapdistance"),
    path("analyze/", views.start_analyze, name="startanalyze"),
    path("analyze/plot/<str:fname>", views.plot_analyze, name="plotanalyze"),
]

django/test_project2/test_project2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("test_polar.urls")),
    # path("", include("test_training2.urls")),
]

django/test_project2/test_project2/templates/adapt.html
<!DOCTYPE html>
{% extends "base.html" %}
{% comment %} <!DOCTYPE html> {% endcomment %}
{% comment %} {% extends "base.html" %} {% endcomment %}
{% load static %}
{% load cache %}
{% load table_filters %}

{% block adapt_block %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>summary</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/test_polar.css" %}">
    
</head>
<body>
  <script src={% static  "js/general.js" %}></script>
  <script src={% static  "js/adapt.js" %}></script>
{% if adaptlapform %}
<form method="POST" action='{% url "test_polar:adaptlapdistance" %}' enctype="multipart/form-data">
  {{ adaptlapform.as_div }}
  {% csrf_token %}
  
  <div class="container">
    <div class="row">
      <div class="col">
        <input type="submit" class="btn btn-primary", value="Commit" method="POST" onclick=showAdaptLap(this)>
      </div>
    </div>
  </form>
  {% endif %} 
</div>
  <button id="to_adapt" class="btn btn-primary" onclick="window.location.href = '/adapt'">To adapt</button>

  
  {% if adaptform %}
  <div class="container">
    <div class="row">
      <div class="col">
        <form method="POST", enctype="multipart/form-data">
          {% comment %} {{form.as_p}} {% endcomment %}
          {{ adaptform.as_p }}
          {% csrf_token %}
          <input type="submit" class="btn btn-primary", value="Commit" method="POST">
        </form>
      </div>
    </div>
  </div>
  {% endif %} 
  {% endblock %}

  
  {% block traintab_block %}
  {%if lapdata%}
  <h3> {{ lapdate|slice:10 }}</h3>
  <table class="shortlaptable" value={{fname}} data-url="{% url 'test_polar:showadaptlap' fname %}">
            
    <th>Lapnr</th><th>Dist.</th><th>Dur.</th><th>Vavg.</th><th>Vavgcorr.</th> 
    {% for lap in lapdata %}
    <tr onclick=showAdaptLap(this)><td>{{ forloop.counter }}</td>
        <td>{{lap.distance|floatformat:0}}</td>
        <td>{{lap.duration|duration2min }}</td>
        <td>{{lap.speed.avg|kmh2minkm }}</td> 
        <td>{{lap.speed.avg_corr|kmh2minkm }}</td>  
    {% endfor %}
  </table>
  {% endif %}
  
  <div class="btn-group-vertical">
    <label for="rb_delete"  value="Delete">Delete training active</label><input type="radio" class="btn btn-primary" id="rb_delete" name="group1" {% if delete_checked %} checked {% endif %}> 
    <label for="rb_update" value="Update" >Update training active</label><input type="radio" class="btn btn-primary"id="rb_update" name="group1" {% if update_checked %} checked {% endif %}>
  </div>


  <table name="traindata">
    <tr>
            <th>Date</th>
            <th>location</th>
            <th>Distance(m)</th>
            <th>vel avg(min/km)</th>
            <th>Hsl avg(bpm)</th>
            <th>training description</th>
        </tr>
        <p>{% cache 360 "training_data" %}
          {% for training in trainingen|dictsort:"startTime" %} 
            <tr value={{training.fname}}
            name="traindata" 
            id="traindata"
            {% if training.trainingtype.roadrace %}  
            class="roadrace"
            {% elif training.trainingtype.easyrun %}  
            class="easyrun"
            {% elif training.trainingtype.sprint %}  
            class="sprint"
            {% elif training.trainingtype.interval == "interval" %}
            class="interval"
            {% elif training.trainingtype.climax %}
            class="climax"
            
            {% endif %}
            data-url="{% url 'test_polar:showadapt' training.fname %}"
            onclick="showAdapt(this)">
            
            <td>{{training.startTime|slice:":10"|weekday}}
  
            </td> 
            
            {% if training.location != None %}
            <td id="location">{{training.location|upper}}</td>
            {% else %}
            <td id="location">not defined</td>
            {% endif %}
            <td>{{training.distance|floatformat:0}}</td>
            <td>{{training.speed.avg|kmh2minkm}}</td>
            <td>{{training.averageHeartRate|floatformat:0}} / {{training.maximumHeartRate|floatformat:0}}
            </td>
            <td id="tdescr" >{{training.trainingdescription.description|linebreaks}}</td>
        </tr>
        {% endfor %}
        {% endcache %}
    </p>
    <br><br>
    {% endblock %}
 
</html>

django/test_project2/test_project2/templates/analyze.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% comment %} {% load cache %} {% endcomment %}
{% load table_filters %}
<html lang="en">
<head>

  {% block analyze_block %}


  <meta charset="utf-8">
  <title>analyze</title>

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/test_polar.css" %}">
    
</head>
<body>
  <script src={% static  "js/general.js" %}></script>
  <script src={% static  "js/analyze.js" %}></script>
  {% comment %} <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> {% endcomment %}
  <script src="{% static 'node_modules/chart.js/dist/chart.umd.js' %} "></script>


  <input type="reset" onclick="resetgraphs()" value= "reset graphs" name="reset">
  <table>
      <tr><th id=ldate1></th><th id=ldate2></th></tr>
      <tr>
      <td class="analyzegraph">
      <div>
        <canvas id="ChartS1"></canvas>
      </div>
    </td>
    {% comment %} </tr>  {% endcomment %}
    <td class="analyzegraph">
      <div>
        <canvas id="ChartS2"></canvas>
      </div>
      </td>  
    </tr>
    <tr>
    </tr>
    <td class="analyzegraph">
      <div>
        <canvas id="ChartH1"></canvas>
      </div>
    </td>
    <td class="analyzegraph">
      <div>
        <canvas id="ChartH2"></canvas>
      </div>
    </td>


    </table>
    <p>{{ ttypes }}</p>
    {% if ttypes %}
    <form id="trainingForm" action="/analyze/?" method="get">
        {% comment %} {% csrf_token %} {% endcomment %}
        <select id="trainingtype" name="ttypes" size="6" onclick="" >
        {% for type_name in ttypes %}
            <option value={{type_name}}>{{type_name}}</option>
        {% endfor %}
      
    </select>
    <input type="submit" id="to_addtt" value="to next page" onclick="toHeadofpage()"> </input>
    </form>
    {% endif %}
    {% endblock %}

{% block traintab_block %}
<table name="traindata">
    <tr>
        <th>Date</th>
        <th>location</th>
        <th>Distance(m)</th>
        <th>vel avg(min/km)</th>
        <th>Hsl avg(bpm)</th>
        <th>training description</th>
    </tr>
      <p>
        {% comment %} {% cache 60 "training_data" %} {% endcomment %}
        {% for training in trainingen|dictsort:"startTime" %} 
          <tr value={{training.fname}}  
          name="traindata" 
          id="traindata"
          {% if training.trainingtype.roadrace %}  
          class="roadrace"
          {% elif training.trainingtype.easyrun %}  
          class="easyrun"
          {% elif training.trainingtype.sprint %}  
          class="sprint"
          {% elif training.trainingtype.climax %}  
          class="climax"
          {% elif training.trainingtype.interval == "interval" %}
          class="interval"
          {% endif %}

          data-url="{% url 'test_polar:plotanalyze' training.fname %}"
          onclick="plotLapdata(this)">


          <td>{{training.startTime|slice:":10"|weekday}}</td> 
          
          {% if training.location != None %}
          <td id="location">{{training.location|upper}}</td>
          {% else %}
          <td id="location">not defined</td>
          {% endif %}
          <td>{{training.distance|floatformat:0}}</td>
          <td>{{training.speed.avg| kmh2minkm}}</td>
          <td>{{training.averageHeartRate|floatformat:0}} / {{training.maximumHeartRate|floatformat:0}}
          </td>
          <td id="tdescr">{{training.trainingdescription.description|linebreaks}}</td>
      </tr>
      {% endfor %}
      {% comment %} {% endcache %} {% endcomment %}
      </p>
    <br><br>
      </table>

    {% endblock %}
</body>

django/test_project2/test_project2/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8" />
    <title>title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
<body>
    <div class="container">
        <header class="d-flex justify-content-center py-3">
          <ul class="nav nav-pills">
            <li class="nav-item"><a href={% url "test_polar:selectcol" %} class="nav-link active" aria-current="page">Home</a></li>
            <li class="nav-item"><a href={% url "test_polar:showpolar" %} 
              class="nav-link">Summary</a></li> 
            <li class="nav-item"><a href="{% url "test_polar:startanalyze" %}" class="nav-link">Analyze</a></li>
            <li class="nav-item"><a href={% url "test_polar:startadapt" %} class="nav-link">Adapt</a></li>
            <li class="nav-item"><a href="#" class="nav-link">About</a></li>
          </ul>
        </header>
      </div>
      {% block adapt_block %}
      {% endblock %}

      {% block summary_block %}
      {% endblock %}
      {% block analyze_block %}
      {% endblock %}


      {% block traintab_block %}
      {% endblock %}

</body>
</html>

django/test_project2/test_project2/templates/home.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% load cache %}
{% load table_filters %}
<html lang="en">
<head>

    {% block summary_block %}
    <meta charset="utf-8">
    <title>summary</title>
    {% block adapt %}
    {% endblock %}
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/test_polar.css" %}">
    
</head>

    <body>
        <form id="collectionform" action="/summary/" method="get">
            <select id="dtable" name="dtable" size="15">
                {% for tab in dbtables %}
                <option value={{ tab }}>{{ tab }}</option>
                {% endfor %}
            </select>
            <input type="submit" id="to_addtt" value="to next page" onclick="toHeadofpage()">
        </form> 
    {% endblock %}
</body>
</html>

django/test_project2/test_project2/templates/summary.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% load cache %}
{% load table_filters %}
{% block summary_block %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>summary</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/test_polar.css" %}">
    
</head>

    <body>
        <script src={% static  "js/general.js" %}></script>
        <script src={% static  "js/summary.js" %}></script>
    
    <div id="lapdata"> 
        {% if lapdata %}
        <h3> {{ lapdate|slice:10 }}</h3>
        <table class="laptable" value={{fname}}>
            
            <th>Lapnr</th> 
            <th>Dur</th> 
            <th>Dist.</th> 
            <th>V avg</th> 
            <th>V avg,<br></br>corr</th> 
            <th>HR avg</th> 
            <th>HR max</th> 
        {% for lap in lapdata %}
            <tr><td>{{ forloop.counter }}</td>
                <td>{{lap.duration|duration2min }}</td>
                <td>{{lap.distance|floatformat:0}}</td> 
                <td>{{lap.speed.avg|kmh2minkm }}</td> 
                <td>{{lap.speed.avg_corr|kmh2minkm }}</td> 
                <td>{{lap.heartRate.avg|floatformat:0}}</td> 
                <td>{{lap.heartRate.max|floatformat:0}}</td> </tr>
        {% endfor %}
            {% endif %}
        </table>
        <div class="info">
        <br> number of run training in table: {{ trainingen|length }} </br>
        </div>
    <p>{{ ttypes }}</p>
    
        {% if ttypes %}
        <form id="trainingForm" action="/summary/" method="get">
            {% comment %} {% csrf_token %} {% endcomment %}
            <select id="trainingtype" name="ttypes" size="6" onclick="" >
            {% for type_name in ttypes %}
                <option value={{type_name}}>{{type_name}}</option>
            {% endfor %}
            
        </select>
        <input type="submit" id="to_addtt" value="to next page" onclick="toHeadofpage()"> </input>
    </form>
    {% endif %}
{% endblock %}

{% block traintab_block %}
<table name="traindata">
    <tr>
            <th>Date</th>
            <th>location</th>
            <th>Distance(m)</th>
            <th>vel avg(min/km)</th>
            <th>Hsl avg(bpm)</th>
            <th>training description</th>
        </tr>
        <p>{% cache 60 "training_data" %}
        <p>
            {% for training in trainingen|dictsort:"startTime" %} 
            <tr value={{training.fname}}  
            name="traindata" 
            id="traindata"
            {% if training.trainingtype.roadrace %}  
            class="roadrace"
            {% elif training.trainingtype.easyrun %}  
            class="easyrun"
            {% elif training.trainingtype.sprint %}  
            class="sprint"
            {% elif training.trainingtype.climax %}  
            class="climax"
            {% elif training.trainingtype.interval == "interval" %}
            class="interval"
            {% endif %}

            data-url="{% url 'test_polar:showlapdata' training.fname %}">
            <td>{{training.startTime|slice:":10"|weekday}}</td> 
            
            {% if training.location != None %}
            <td id="location">{{training.location|upper}}</td>
            {% else %}
            <td id="location">not defined</td>
            {% endif %}
            <td>{{training.distance|floatformat:0}}</td>
            <td>{{training.speed.avg| kmh2minkm}}</td>
            <td>{{training.averageHeartRate|floatformat:0}} / {{training.maximumHeartRate|floatformat:0}}
            </td>
            <td id="tdescr" 
            onclick="showLapdata(this)">{{training.trainingdescription.description|linebreaks}}</td>
        </tr>
        {% endfor %}
        {% endcache %}
        </p>
    <br><br>
    {% endblock %}
    
</body>
</html>

django/test_project2/test_project2/templates/testpage.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>testpage</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    <style>
        #textblok {
            border: 1px solid #999;
            padding: 10px;  /* Add padding for better visual appearance */
            background-color: yellow
        }
    </style>
    
</head>
{% block body_block %}
<body>
    <script src={% static  "js/training_test.js" %}></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    <!-- Content here -->
    <h1>Testpage, try to put an image</h1>
    
    <img src="{% static "images/knmirotterdam_220911_20.png" %}"  id="grafje", width="500" height="600", alt="Oh nooo!">

    
    <div class="container">
        <div class="row">
            <div class="col-6">

                <label for="to_addtt">To add trainingtype</label>
                <a href={% url 'test_training2:addttype' %}>
                    <input type="submit" id="to_addtt" value="to next page"> </input>
                </a>             
            </div>
        </div>
        <p></p>
        <div class="row">
            <div class="col-4">
                <div class="col-4">
                    <label for="trainingtype">Choose trainingtype:</label>
                </div>
                <p>{{ ttypes}}</p>
                <select id="trainingtype" name="ttypes" size="3" onclick="updateText2()">
                    {% if  ttypes %}
                        {% for t in ttypes %}
                            <option value={{ t.type_name}}>{{ t.datapath|cut:"C:/TEMP\knmirotterdam_"|slice:6}}</option>
                        {% endfor %}
                        {% else %}
                            <option value="No Choice">No Choice</option>
                    {% endif %}
                </select>
            </div>
            <div class="col-6">
            </div>
            <div class="col-6">
                <button id="button" onclick="updatePlaatje()">Select graph</button>
            </div>
            
            <p id="textblok" border="1px solid #999">sss </p>
        </div>
    </div>
    </div>
{% endblock %}

</body>
</html>