django/login_project/login_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from loginregister import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("clienthandling/", include("loginregister.urls")),
    path("", views.base, name="base"),
    # path("home/", views.logout),
]

django/login_project/loginregister/urls.py
from django.urls import path, re_path
from loginregister import views

app_name = "loginregister"

urlpatterns = [
    # re_path(r"^add_ttype/$", views.add_ttype, name="addttype")
    # path("", views.add_ttype, name="addttype"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.registration, name="register"),
]

django/login_project/loginregister/models.py
from django.db import models

# from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.SET_NULL)
    portfolio = models.URLField(blank=True)
    inlogname = models.TextField(default="")
    databasename = models.TextField(default="")
    password = models.TextField(default="")
    host = models.TextField(default="localhost")
    port = models.IntegerField(default=27017)

    def __str__(self):
        return self.user.get_username()

    @classmethod
    def get_entry(cls, idnr):
        try:
            return cls.objects.get(user_id=idnr)
        except cls.DoesNotExist:
            return None

django/login_project/loginregister/forms.py
from django import forms
from .models import UserProfile
from django.core import validators
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "password", "email")


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("portfolio",)

django/login_project/loginregister/views.py
import asyncio
import subprocess
import webbrowser
from pathlib import Path
from django.contrib.auth.decorators import login_required
from typing import Union

# Create your views here.
from django.shortcuts import render  # , redirect
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.contrib.auth import get_user_model

from .models import UserProfile
from .forms import UserProfileForm, UserForm
from .utils import create_settings, create_toml  # , replace_input

# from loginregister.models import Trainingtype  # , PolarModel#, Testpage, PolarModel
# import main_start_djangopolar as startpolar


@login_required
def logout_user(request: HttpRequest) -> HttpResponse:
    logout(request)
    return HttpResponseRedirect("base.html")


def base(request: HttpRequest) -> HttpResponse:
    return render(request, "base.html")


def login_user(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        print(request.POST)
        username = request.POST.get("username")
        password = request.POST.get("password")
        usermodel = get_user_model()
        user = usermodel._default_manager.get_by_natural_key(username)

        # if authentication results in false, it doesn't give a clue why.
        user = authenticate(username=username, password=password)
        # print(user.check_password(password))
        # print(
        #     ModelBackend().authenticate(request, password=password, username=username)
        # )

        if user:
            if user.is_active:
                login(request, user)
                idnr = user.pk
                userprofile = UserProfile.get_entry(idnr)
                # print(x)
                create_settings(userprofile)
                create_toml(userprofile)
                asyncio.run(startpolar(request))
                return render(request, "base.html", {"logedin": True})
            else:
                HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("login failed")
            return HttpResponse("LOGIN FAILED")

    return render(request, "login.html")


def registration(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        userform = UserForm(data=request.POST)
        profileform = UserProfileForm(data=request.POST)
        if userform.is_valid() and profileform.is_valid():
            user = userform.save()
            user.set_password(user.password)
            user.save()

            profile = profileform.save(commit=False)
            profile.user = user
            # if profile_pics in request.FILES:
            #     profile.profile_pic = request.FILES["profile_pic"]
            profile.save()
            # registered = True
            context = None
        else:
            print(userform.errors, profileform.errors)
            # registered = False
            context = None
        return render(request, "register.html", context=context)
    else:
        userform = UserForm()
        profileform = UserProfileForm()
        context = {"userform": userform, "profileform": profileform}
        # registered = False
        return render(request, "register.html", context=context)


@login_required
async def runserver_polar(request):
    rootpath = Path(__file__).parent.parent.parent.resolve()
    polarpath = Path(__file__).parent.parent.resolve()

    settingfile = "test_project2.settings"

    # os.system(
    #     "python django/test_project2/manage.py runserver "
    #     + "--settings="
    #     + settingfile
    #     + " "
    #     + "8001"
    # )
    process = subprocess.Popen(
        [
            # os.path.join(rootpath, "polar_env/Scripts/activate"),
            "python",
            "django/test_project2/manage.py",
            "runserver",
            "--settings=" + settingfile,
            "--noreload",
            "8001",
        ],
        shell=True,
        # stdout=open("stdout", "w"),
        # stderr=open("stdout", "w"),
    )
    print(process.poll())


def openpolar():
    webbrowser.open_new_tab("http://127.0.0.1:8001/home")


@login_required
async def startpolar(request):
    task1 = asyncio.create_task(runserver_polar(request))
    openpolar()
    await task1

django/login_project/login_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>LOGIN</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/test_polar.css" %}">
    
</head>

<body>
{% if logedin %}
<h1>LOGED IN!!!!</h1>

{% else%}
<div>
    <p>
    <label for="regis">Registreer!!</label>
    <a href="{% url 'loginregister:register' %}" id="regis">Click here</a>
    </p>
    <p>
    <label for="login">Login!!</label>
    <a href="{% url 'loginregister:login' %}" id="login">Click here</a>
    </p>
</div>

{% endif %}
</body>

django/login_project/login_project/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>LOGIN</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/test_polar.css" %}">
    
</head>

<body>
<p>lalala</p>
{% comment %} <img src="{% static 'images/knmirotterdam_220616_11.png' %}" height="300"> {% endcomment %}
<form class="login"  method="post">
    {% comment %} {% url 'loginregister:login' %}  {% endcomment %}
    {% csrf_token %}
    <p>
    <label for="username" placeholder="Username">Username!</label>
        <input type="text" name="username" >
    </p>
    <p>    
        <label for="username" placeholder="password">Password!</label>
    <input type="password" name="password">
    </p>
<input type="submit" value="submit">
</form>

</div>
</body>
</html>

django/login_project/login_project/templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <meta charset="utf-8">
    <title>LOGIN</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/test_polar.css" %}">
    
</head>

<body>
<p>lalala</p>
<a href="http://127.0.0.1:8001/home" class="btn btn-primary">Go to Home</a>
<div>
"{% if registered %}"
<h1>Thank You</h1>

{% else %}
<h1>Register here!</h1>
<form method="POST" action='{% url "loginregister:register" %}'enctype="multipart/form-data">
    {% csrf_token %}
    {{ userform.as_p }}
    {{ profileform.as_p }}
    <input type="submit" value="register">
<form>    
{% endif %}
</div>

<div>
<img src="{% static 'images/knmirotterdam_220616_11.png' %}" height="300">
</div>
</body>
</html>