django/test_project/test_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("test_training.urls")),
    ]

django/test_project/test_training/urls.py
from django.urls import path, re_path
from test_training import views

app_name = "test_training"

urlpatterns = [
    path('training/', views.select_ttype, name="testpage"),
    path('select_ttype/', views.select_ttype2, name="selectttype"),
    # re_path(r"^add_ttype/$", views.add_ttype, name="addttype")
    path("add_ttype/", views.add_ttype, name="addttype"),
    # path("polar/", views.show_polar, name="showpolar"),
    ]

django/test_project/test_training/models.py
from django.db import models
from djongo import models as mongomod

# Create your models here.

# class PolarModel(mongomod.Model):
#     # garminfit = mongomod.JSONField()
#     sport = mongomod.CharField(max_length=256, default="RUNNING")
#     class Meta:
#         db_table = "testdatabase"
#         app_label= "test_training"
        # managed = False
        # using = "mongodb"


class Trainingtype(models.Model):
    type_name = models.CharField(max_length=50, unique=True, primary_key=True)
    # image = models.FileField(max_length=256)
    datapath = models.FilePathField(max_length=256, path="C:/TEMP")


# class Trainingtype2(models.Model):
#     type_name = models.CharField(max_length=50, unique=True, primary_key=True)
#     image = models.FileField(max_length=256)
#     datapath = models.FilePathField(max_length=256, path="C:TEMP")


class Testpage(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    text = models.CharField(max_length=20)
    date = models.DateField()

django/test_project/test_training/views.py
from typing import Union
# Create your views here.
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest,HttpResponseRedirect
from .forms import TrainingForm, TrainingModelForm

from test_training.models import Trainingtype #, Testpage, PolarModel


# def show_polar(request: HttpRequest) -> HttpRequest:
#     if request.method == "GET":
#         print(request.body)
#     training = PolarModel.objects.all()
#     print(training)
#     return render(request, "polar.html")

def select_ttype(request: HttpRequest) -> HttpRequest:
    if request.method == "GET":
        print(request.body)
    training = Trainingtype.objects.all()
    trainingtypes = {"trainingtypes": training}
    # # return HttpResponse("<em> My second X-app!</em>")
    return render(request, "testpage.html", context=trainingtypes)


def _get_typenames() -> list:
    trainings = Trainingtype.objects.all()
    type_names = [t.type_name for t in trainings ]
    print(type_names)
    return  type_names


def select_ttype2(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        type_names = _get_typenames()
        return render(request,"get_ttype.html",  context={"trainingtypes": type_names})

    elif request.method == "POST":
        # print(request.POST)
        trainingtypes = _get_typenames()
        print(request.POST["type_name"])
        trainsel = Trainingtype.objects.filter(type_name=request.POST["type_name"])
        print(trainsel[0])
        return render(request, "get_ttype.html", context={"datapath": trainsel[0].datapath, "trainingtypes": trainingtypes})

    else:
        print("xx")
        return render(request, "get_ttype.html")

def add_ttype(request) -> Union[HttpResponse, HttpResponseRedirect]:
    form  = TrainingModelForm()
    # print(dir(form))
    if request.method == "POST":
        print(request.POST)
        form = TrainingModelForm(request.POST,  request.FILES)
        if form.is_valid():
            print(form.cleaned_data)
            form.save(commit=True)
        return redirect(select_ttype)
            
    return render(request, "add_ttype.html", {"form": form})

django/test_project/test_project/templates/testpage.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>testpage</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

        <style>
            #textblok {
              border: 1px solid #999;
              padding: 10px;  /* Add padding for better visual appearance */
              background-color: yellow
            }
          </style>

    </head>
{% block body_block %}
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    <!-- Content here -->
    <h1>Testpage, try to put an image</h1>
    
    {% comment %} <img src="{% static "images/Dia1.JPG" %}" id="grafje",width="500" height="350", alt="Oh nooo!"> {% endcomment %}
    <img src="{% static "images/knmirotterdam_220911_20.png" %}"  id="grafje", width="500" height="600", alt="Oh nooo!">

    
    <div class="container">
        <div class="row">
            <div class="col-6">

                <label for="to_addtt">To add trainingtype</label>
                <a href={% url 'test_training:addttype' %}>
                    <input type="submit" id="to_addtt" value="to next page"> </input>
                </a>             
            </div>
        </div>
        <p></p>
        <div class="row">
            <div class="col-4">
                <div class="col-4">
                    <label for="trainingtype">Choose trainingtype:</label>
                </div>
                <p>{{ trainingtypes|unordered_list }}</p>
                <select id="trainingtype" name="ttypes" size="3" onclick="updateText2()">
                    {% if  trainingtypes %}
                        {% for t in trainingtypes %}
                        {% comment %} <option value="road race">Road Race</option> {% endcomment %}
                            {% comment %} <option value={{ t.type_name}}>{{ t.image|cut:"knmirotterdam_" }}</option> {% endcomment %}
                            {% comment %} <option value={{ t.type_name}}>{{ t.image|cut:"knmirotterdam_" }}</option> {% endcomment %}
                            {% comment %} <option value={{ t.type_name}}>{{ t.datapath|length }}_{{ t.image|cut:"knmirotterdam_" }}</option> {% endcomment %}
                            {% comment %} <option value={{ t.type_name}}>{{ t.image|cut:"knmirotterdam_"|cut:".png"}}</option> {% endcomment %}
                            <option value={{ t.type_name}}>{{ t.image|cut:"knmirotterdam_"|slice:6}}</option>
                        {% endfor %}
                        {% else %}
                            <option value="No Choice">No Choice</option>
                    {% endif %}
                </select>
            </div>
            <div class="col-6">
                {% comment %} <p>{{  }}</p> {% endcomment %}
            </div>
            <div class="col-6">
                <button id="button" onclick="updatePlaatje()">Select graph</button>
            </div>
            
            <p id="textblok" border="1px solid #999">sss </p>
            <script src={% static  "/js/training_test.js" %}></script>
            {% comment %} <script src="{% static "training_test.js" %}"></script> {% endcomment %}
        </div>
    </div>
    </div>
{% endblock %}

</body>
</html>